[tools]
python = "3.14"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.requirements]
description = "Install dependencies"
alias = "i"
run = "pip install -U -r requirements.txt"
